import Head from 'next/head'
import {GuestLayout} from "@/layout";
import {
    Badge,
    Box,
    BoxProps,
    Button,
    Center,
    Container,
    createStyles,
    Flex,
    Grid,
    Group,
    Image,
    Paper,
    PaperProps,
    rem,
    SimpleGrid,
    Spoiler,
    Stack,
    Text,
    ThemeIcon,
    ThemeIconProps,
    Title,
    Tooltip, UnstyledButton, useMantineTheme
} from "@mantine/core";
import Link from "next/link";
import {PATH_DASHBOARD, PATH_DOCS} from "@/routes";
import {
    IconAdjustmentsHorizontal, IconArrowRight, IconBook, IconChevronDown, IconChevronUp,
    IconColorSwatch,
    IconDevices,
    IconFolderCode,
    IconScaleOutline,
    IconSettingsCog
} from "@tabler/icons-react";
import React from "react";
import CountUp from "react-countup";
import {useMediaQuery} from "@mantine/hooks";

const useStyles = createStyles((theme) => ({
    hero: {
        backgroundColor: theme.black,
        color: theme.white,
        paddingTop: `calc(${theme.spacing.xl} * 4)`,
        paddingBottom: `calc(${theme.spacing.xl} * 4)`,
        paddingLeft: `calc(${theme.spacing.xl} * 4)`,
        paddingRight: `calc(${theme.spacing.xl} * 4)`,

        [theme.fn.smallerThan('sm')]: {
            paddingTop: `calc(${theme.spacing.xl})`,
            paddingBottom: `calc(${theme.spacing.xl})`,
            paddingLeft: `calc(${theme.spacing.xl})`,
            paddingRight: `calc(${theme.spacing.xl})`,
        },
    },

    title: {
        fontWeight: 800,
        fontSize: rem(40),
        letterSpacing: rem(-1),
        marginBottom: theme.spacing.xs,

        [theme.fn.smallerThan('xs')]: {
            fontSize: rem(28),
            textAlign: 'left',
        },
    },

    highlight: {
        color: theme.colors[theme.primaryColor][5],
    },

    stackControl: {
        textTransform: 'capitalize',
        backgroundColor: theme.colors.dark[6],
        color: theme.white,
        padding: `${rem(6)} ${rem(10)}`,
        borderRadius: theme.radius.md
    },

    variantImg: {
        maxHeight: rem(280),
        width: '100%',
        objectFit: 'contain',
    },

    variantTitle: {
        textAlign: 'center',
        marginTop: theme.spacing.md,
        fontWeight: 600
    }
}))


const PAPER_PROPS: PaperProps = {
    p: "md",
    shadow: "md",
    radius: "md",
    sx: {
        height: '100%',
        backgroundColor: 'transparent'
    }
}

const THEME_ICON_PROPS: Omit<ThemeIconProps, 'children'> = {
    variant: "light",
    size: 48
}

export default function Home() {
    const {classes, theme} = useStyles()
    const tablet_match = useMediaQuery('(max-width: 768px)');

    const IMAGE_PAPER_PROPS: PaperProps = {
        p: 'md',
        sx: {
            height: '100%',
            backgroundColor: 'transparent',

            '&:hover': {
                'img': {
                    boxShadow: theme.shadows.lg,
                    transition: 'all ease 150ms',
                    transform: 'scale(1.03)',
                }
            }
        }
    }

    const BOX_PROPS: BoxProps = {
        mt: 120,
        pb: 80,
        px: tablet_match ? 20 : 48,
    }

    return (
        <>
            <Head>
                <title>Admin DashBoard</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                

            </Head>
            <GuestLayout>
                <Box className={classes.hero}>
                    <Grid>
                        <Grid.Col lg={6}>
                            <Stack>
                                
                                
                                <Text>Admin Dashboard demo</Text>
                                <Group my="lg">
                                    <Button
                                        component={Link}
                                        href={PATH_DASHBOARD.default}
                                        size="md"
                                        rightIcon={<IconArrowRight/>}
                                    >
                                        Go to Dashboard
                                    </Button>
                                    
                                </Group>
                                
                            </Stack>
                        </Grid.Col>
                        <Grid.Col lg={6}>
                            <Image
                                src="/thumbnail-img-b.jpg"
                                alt="/"
                            />
                        </Grid.Col>
                    </Grid>
                </Box>
                
                
            </GuestLayout>
        </>
    )
}
